version: '3'

services:
  api:
    build: api
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "8080:8080"

  client:
    build: 
      context: web
      dockerfile: Dockerfile.dev
    command: ["serve", "-s", "build"]
    tty: true
    volumes:
      - ./web:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  node-modules:
