FROM node:lts-alpine as builder
WORKDIR /frontend

COPY . .
RUN echo $(node --version)
RUN echo $(npm --version)
RUN npm install
RUN npm run build
RUN npm install -g serve
#CMD ["serve", "-s", "build"]
